<a href="https://colab.research.google.com/github/victorezealuma/bank-transaction-analysis/blob/main/BankingDataCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Cleaning in Pandas

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv(r"/content/drive/MyDrive/bank_transactions.csv")

df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount (INR)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,183734,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1048566,T1048567,C8337524,5/3/84,M,PUNE,75734.42,18/9/16,181222,1166.0

In [9]:
df = df.rename(columns={'TransactionAmount (INR)': 'TransactionAmount(NGN)'})


df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount(NGN)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,143207,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,141858,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,142712,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,142714,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,181156,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,NEW DELHI,7635.19,18/9/16,184824,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,183734,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,183313,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,184706,1000.0
1048566,T1048567,C8337524,5/3/84,M,PUNE,75734.42,18/9/16,181222,1166.0

In [10]:
df['TransactionTime'] = df['TransactionTime'].apply(lambda x: str(x))

df['TransactionTime'].apply(lambda x: x[0:2] + ':' + x[2:4] + ':'+ x[4:6])

df['TransactionTime'] = df['TransactionTime'].apply(lambda x: x[0:2] + ':' + x[2:4] + ':'+ x[4:6])

df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount(NGN)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,14:32:07,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,14:18:58,27999.0
2,T3,C4417068,26/11/96,F,MUMBAI,17874.44,2/8/16,14:27:12,459.0
3,T4,C5342380,14/9/73,F,MUMBAI,866503.21,2/8/16,14:27:14,2060.0
4,T5,C9031234,24/3/88,F,NAVI MUMBAI,6714.43,2/8/16,18:11:56,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,NEW DELHI,7635.19,18/9/16,18:48:24,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,18:37:34,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,18:33:13,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,18:47:06,1000.0
1048566,T1048567,C8337524,5/3/84,M,PUNE,75734.42,18/9/16,18:12:22,1166.0

In [11]:
data = {'CustLocation': ['MUMBAI', 'NEW DELHI', 'BANGALORE', 'GURGAON','DELHI','PUNE','NAVI MUMBAI']}

df['CustLocation'] = df['CustLocation'].replace('MUMBAI', 'LAGOS ISLAND')
df['CustLocation'] = df['CustLocation'].replace('NEW DELHI', 'IKEJA')
df['CustLocation'] = df['CustLocation'].replace('BANGALORE', 'YABA')
df['CustLocation'] = df['CustLocation'].replace('GURGAON', 'IKORODU')
df['CustLocation'] = df['CustLocation'].replace('DELHI', 'LEKKI')
df['CustLocation'] = df['CustLocation'].replace('PUNE', 'ABULE-EGBA')
df['CustLocation'] = df['CustLocation'].replace('NAVI MUMBAI', 'MUSHIN')

df

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount(NGN)
0,T1,C5841053,10/1/94,F,JAMSHEDPUR,17819.05,2/8/16,14:32:07,25.0
1,T2,C2142763,4/4/57,M,JHAJJAR,2270.69,2/8/16,14:18:58,27999.0
2,T3,C4417068,26/11/96,F,LAGOS ISLAND,17874.44,2/8/16,14:27:12,459.0
3,T4,C5342380,14/9/73,F,LAGOS ISLAND,866503.21,2/8/16,14:27:14,2060.0
4,T5,C9031234,24/3/88,F,MUSHIN,6714.43,2/8/16,18:11:56,1762.5
...,...,...,...,...,...,...,...,...,...
1048562,T1048563,C8020229,8/4/90,M,IKEJA,7635.19,18/9/16,18:48:24,799.0
1048563,T1048564,C6459278,20/2/92,M,NASHIK,27311.42,18/9/16,18:37:34,460.0
1048564,T1048565,C6412354,18/5/89,M,HYDERABAD,221757.06,18/9/16,18:33:13,770.0
1048565,T1048566,C6420483,30/8/78,M,VISAKHAPATNAM,10117.87,18/9/16,18:47:06,1000.0
1048566,T1048567,C8337524,5/3/84,M,ABULE-EGBA,75734.42,18/9/16,18:12:22,1166.0

In [12]:
specific_location = ['LAGOS ISLAND', 'IKEJA', 'YABA', 'IKORODU','LEKKI','ABULE-EGBA', 'MUSHIN']

df[df['CustLocation'].isin(specific_location)]

,TransactionID,CustomerID,CustomerDOB,CustGender,CustLocation,CustAccountBalance,TransactionDate,TransactionTime,TransactionAmount(NGN)
2,T3,C4417068,26/11/96,F,LAGOS ISLAND,17874.44,2/8/16,14:27:12,459.0
3,T4,C5342380,14/9/73,F,LAGOS ISLAND,866503.21,2/8/16,14:27:14,2060.0
4,T5,C9031234,24/3/88,F,MUSHIN,6714.43,2/8/16,18:11:56,1762.5
6,T7,C7126560,26/1/92,F,LAGOS ISLAND,973.46,2/8/16,17:38:06,566.0
7,T8,C1220223,27/1/82,M,LAGOS ISLAND,95075.54,2/8/16,17:05:37,148.0
...,...,...,...,...,...,...,...,...,...
1048556,T1048557,C3414578,10/9/90,F,IKORODU,27592.70,18/9/16,18:49:32,2000.0
1048560,T1048561,C5028150,24/5/80,M,ABULE-EGBA,464.87,18/9/16,18:46:32,3000.0
1048561,T1048562,C1034220,19/11/92,M,YABA,1212.70,18/9/16,18:47:34,1500.0
1048562,T1048563,C8020229,8/4/90,M,IKEJA,7635.19,18/9/16,18:48:24,799.0
1048566,T1048567,C8337524,5/3/84,M,ABULE-EGBA,75734.42,18/9/16,18:12:22,1166.0

In [13]:

df.to_csv('clean_data.csv', index=False)